apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: student-service-db
  namespace: student-service-database
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.10-minimal-trixie
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
  bootstrap:
    initdb:
      database: student_service
      owner: student_service
      secret:
        name: student-service-db-app
  storage:
    size: 5Gi
    storageClass: local-path
