apiVersion: v1
kind: Secret
metadata:
    name: student-service-db-app
    namespace: student-service-database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ja3dfVE+Qmlfjq+luTLt,iv:shxqDYnP1mOa0gUXsHSSvnN0Nr1HW5CG0hmcNjs0oWg=,tag:KDjceH3x/FunJWz+bEMoUA==,type:str]
    password: ENC[AES256_GCM,data:lKGlhfBByV4RBjwiCX4L6oRJt+QVSWDqGtdlbfEI1TdOjwX5DOIOyRiySV4+lK31gIeUc/VQwqk6ej2AJVVXlw==,iv:UhxAClszqnj0OtdF5LkgYf0uU3fLZDAq2FOSIZ77HNE=,tag:G4SmVYAIMRNCvrS/g+EwbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOVRna3FUZ1F0T1RCSzZX
            R1lmZ1RrTkhMTWJJbkdvV1RLMVpqSTNMYUNZClZKdlZOTWJhN240S1V0SUtVM1pM
            aUtvWkVibmZDekJhYUhlWTk0V0k3dVEKLS0tIHFSSVBpaEZOeEVJdmJnSlZWMUlr
            QmJrSWFlU05Bdno4YXBkMC9IR2IxZHMKGr1EWAlTDxICUDzq+yI9hFs9ar349heJ
            JOoXYa5WE5BvSRNHcTUuqjiuycqBoUF2ayxCQ0HE2ZMkh8NGP/7gSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nsru6fkuqz9ys6z0tpw05psp5paytua6yrykscvn2akh5e4casgs3wnq6w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T14:08:53Z"
    mac: ENC[AES256_GCM,data:RIcLiwGQ6gQqdFve4atEhWKCNnweaz0C5PuHiUcjAnp4hCQAnaxTOehDIMae0uDQ8cMKpJ4ImsT/lnsnas+Hva64PgXZsjih8KFeWH04CKWAiWfhq1l1GObfdq9BTQdFI0Hejr0WU2nGtnTqvfawMAr+Q9+CTIg8voQ4rbsWH58=,iv:LHyX7PucR94V/bb7oYApExo/tD0lruOy1tcfBnT7Gfo=,tag:N9As17x7n0vQ86yGuTc1AQ==,type:str]
    version: 3.13.3
