apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database-credentials.sops.yaml
  - backend-database-url.sops.yaml
  - cluster.yaml
  - networkpolicy.yaml
