# Generated by Django 6.0.5 on 2026-06-28 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='professor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_no', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('index_no', models.CharField(max_length=30, unique=True)),
                ('current_year_of_study', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('current_year_of_study__gte', 1), ('current_year_of_study__lte', 8)), name='student_current_year_of_study_between_1_and_8')],
            },
        ),
    ]
