# Generated by Django 6.0.5 on 2026-07-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_professorprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.curriculum'),
        ),
    ]
