from .base import *  # noqa: F403

SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = False
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")

PROMETHEUS_METRICS_EXPORT_ADDRESS = "0.0.0.0"
PROMETHEUS_METRICS_EXPORT_PORT = 8001
