STUDENT_EMAIL = "student@example.com"
STUDENT_PASSWORD = "student123"
STUDENT_INDEX_NO = "IN 47/2020"

PROFESSOR_EMAIL = "professor@example.com"
PROFESSOR_PASSWORD = "professor123"
PROFESSOR_EMPLOYEE_NO = "P001"
