apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: student-service-tls
  namespace: student-service
spec:
  secretName: student-service-tls
  dnsNames:
    - student-service.internal
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: student-service-ca
