apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: student-service-frontend
  namespace: student-service
  labels:
    app.kubernetes.io/name: student-service-frontend
    app.kubernetes.io/component: web
spec:
  parentRefs:
    - name: shared-gateway
      namespace: gateway-system
      sectionName: http
  hostnames:
    - ingress.student-service.internal
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: student-service-frontend
          port: 80
