apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: student-service-dns-pool
spec:
  blocks:
    - start: 192.168.1.242
      stop: 192.168.1.242
  serviceSelector:
    matchLabels:
      io.kubernetes.service.name: student-service-dns
      io.kubernetes.service.namespace: kube-system
