apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: frontend-pool
spec:
  blocks:
    - start: 192.168.1.240
      stop: 192.168.1.240
  serviceSelector:
    matchLabels:
      io.kubernetes.service.name: student-service-frontend
      io.kubernetes.service.namespace: student-service
