apiVersion: v1
kind: ConfigMap
metadata:
  name: student-service-backend-config
  namespace: student-service
data:
  DJANGO_ALLOWED_HOSTS: "student-service-backend,\
    student-service-backend.student-service,\
    student-service-backend.student-service.svc,\
    student-service-backend.student-service.svc.cluster.local"
  DJANGO_CORS_ALLOWED_ORIGINS: ""
  DJANGO_CSRF_TRUSTED_ORIGINS: ""
