COURSE_CODE = "TEST01"
COURSE_NAME = "Test Course"
COURSE_ESPB = 5

CURRICULUM_CODE = "IE-BSC"
CURRICULUM_NAME = "Information Engineering"
CURRICULUM_DURATION = 4

SCHOOL_YEAR = "2020/2021"
SEMESTER = 1
