# Generated by Django 6.0.5 on 2026-06-28 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_professorprofile_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('espb', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='accounts.professorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('degree_level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral')], max_length=30)),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('duration__gte', 1), ('duration__lte', 6)), name='curriculum_duration_between_1_and_6')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_mandatory', models.BooleanField(default=True)),
                ('school_year', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='School year must use the YYYY/YYYY format.', regex='^\\d{4}/\\d{4}$')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_courses', to='academics.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='academics.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='School year must use the YYYY/YYYY format.', regex='^\\d{4}/\\d{4}$')])),
                ('semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('dropped', 'Dropped'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=40)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('espb__gte', 1), ('espb__lte', 60)), name='course_espb_between_1_and_60'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.UniqueConstraint(fields=('curriculum', 'course', 'school_year'), name='uq_curriculum_course_school_year'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.CheckConstraint(condition=models.Q(('semester__gte', 1), ('semester__lte', 12)), name='curriculum_course_semester_between_1_and_12'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'school_year'), name='uq_student_course_school_year'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('semester__gte', 1), ('semester__lte', 12)), name='enrollment_semester_between_1_and_12'),
        ),
    ]
