# Generated by Django 6.0.5 on 2026-08-16 21:39

import django.core.validators
from django.db import migrations, models


def reject_duplicate_curriculum_courses(apps, schema_editor):
    CurriculumCourse = apps.get_model("academics", "CurriculumCourse")
    duplicate_pairs = (
        CurriculumCourse.objects.values("curriculum_id", "course_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    if duplicate_pairs.exists():
        raise RuntimeError(
            "Cannot remove school year: duplicate curriculum/course pairs exist. "
            "Remove duplicates, then retry."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(reject_duplicate_curriculum_courses, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='curriculumcourse',
            name='uq_curriculum_course_school_year',
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='school_year',
            field=models.CharField(
                db_default='2025/2026',
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message='School year must use the YYYY/YYYY format.',
                        regex='^\\d{4}/\\d{4}$',
                    )
                ],
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='curriculumcourse',
                    name='school_year',
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.UniqueConstraint(fields=('curriculum', 'course'), name='uq_curriculum_course'),
        ),
    ]
