apiVersion: v1
kind: ConfigMap
metadata:
  name: student-service-dns
  namespace: tailnet-dns
data:
  Corefile: |
    student-service.internal:53 {
        errors
        health :8080 {
            lameduck 5s
        }
        ready :8181
        file /etc/coredns/db.student-service.internal {
            reload 30s
            reload_by_mtime
        }
        reload
    }
  db.student-service.internal: |
    $ORIGIN student-service.internal.
    @ 60 IN SOA . . 2026082201 3600 600 86400 60
    @ 60 IN A 192.168.1.240
    harbor 60 IN A 192.168.1.241
