apiVersion: v1
kind: Service
metadata:
  name: student-service-dns
  namespace: tailnet-dns
  labels:
    app.kubernetes.io/name: student-service-dns
    app.kubernetes.io/component: dns
  annotations:
    lbipam.cilium.io/ips: 192.168.1.242
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: student-service-dns
    app.kubernetes.io/component: dns
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
