apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ca
  namespace: arc-runners
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFFDCCAvygAwIBAgIUJUWzCvx9eagsLxzaiLSPLczjfkYwDQYJKoZIhvcNAQEN
    BQAwIjEgMB4GA1UEAxMXc3R1ZGVudC1zZXJ2aWNlLXJvb3QtY2EwHhcNMjYwNDIy
    MjI0NzQ4WhcNMzYwNDE5MjI0NzQ4WjAiMSAwHgYDVQQDExdzdHVkZW50LXNlcnZp
    Y2Utcm9vdC1jYTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMNzdXtL
    uZB1moKN6EVjjozf9STQZchKqGCvDRwralp2FwkYbGlFExkeuHtbniQ6/Zpl+8Fr
    cxG8AGMlVEGUDdC3rtk0C2wUQ+QIWtgCkOJslCKYQd00wuOAUgvTDeneXY640iWI
    GuOOwC8AmgkTsOB7QodbGFCIT9jnwXHFO3Vu4Ub+XOA3VDSpbIipkUW9pqeQ/73u
    giU5FO4SXn3JNlDtnbu9pmwe9XcJKFNTIo7NktI5AvDm4rAfgkkl/WuQf9BGT3qN
    qL7q01zjxo+iAmPL4JwekCAbuYGbcBGx02T5AYbHkRSIzIVymKkx2PvtZFEmYCJ+
    1uQES8fcA8FZoLcoCdMeGESJTwDppeq80OiksT2KHccOGeEsde9dMrBeimH7ko4q
    yF26pMKo/KlwP0L1mq3k6mOS12xoLuLV91Hx4egLX+x8QQxa5w6gkiV3cF47QIjR
    gr6P1H0Er7BANymEidBPZr7t8+mGToKEHuRSfxt1n3XlgVDLO6LiU2G8yu821kGS
    0CL+sZaPTrRako2u/KOm+HTylOqR5b5wdksTHqMGOC1O4FtJs/GJyvJmcWC0XpbM
    J36yi6pDb+pKLX8eICiEHC+LghFNa1RdCpR6M0gRa7kQhjhsvoq5BV/vdWRkRY3u
    YJbsZNm4pK4wf/Cut10nla56cM/NSzOn4ozvAgMBAAGjQjBAMA4GA1UdDwEB/wQE
    AwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBT2uW7+RMDPm5Jtgv1axyMP
    QgUd+TANBgkqhkiG9w0BAQ0FAAOCAgEAVBpOROfI2K0+INRsirbFOl7v3N8J0WlC
    PoAZ/vneF553kGeVCMv+5nOUryHYtNcIStArZjCyre81w8Z31adEg5an/EzuNuGx
    5pPCE15TaBqAEmWdRKDIKM/ywZ2jlQyY7cJjMPQce/K89v5cxaxUIRPLvsBQPOrv
    lWofz/VAxWSPIanunmrYMROyhgkJNOqUiDwQrr6QP8o247CuJV8kPzMIHDoi9JRR
    DhWLvYXvY3m+TmkhUZZMd0AlCB7U5Um28fgGw6KBdlyy1o5ecxUVgD2JU5V3kYDe
    Ph0HTM5jsNwOUzXKVVP+XxxtCtJtIRiayciRzuBXqNmgcl/u6koIzmR6VIl57pMy
    D1KTMwicVZ6DcCVNCkQkaI6DSHWUw5puE90DduoBaf3CrnJF9iQXp9jriok4+kKE
    yZ7lOIgktbcfk55s121Vm+7JnFa6yxllIBckEJxHdo+2am82RQRU6t2KFgNs73gp
    3xI6QCnqWRcnGstD/IUJ6n0MZyrOm5BDj7ZGVf/0earJYu7Dbg5kDFMHdkWChno7
    Q2SoNblSBuqT+xL5kkPwdTlszqSLC0u/6TnNMruapjZhDMrbpZDsurSU63SZwr1B
    V4rcJgvpZP+ELaYd8kjUpjXNJ5FnBbn22AvjOHw7qPUX5mwEz0PFTsvIziRrKGcE
    bZen1YzENns=
    -----END CERTIFICATE-----
