# Generated by Django 6.0.5 on 2026-07-02 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0002_professorprofile_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='accounts.professorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('graded', 'Graded'), ('active', 'Active')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_registrations', to='accounts.studentprofile')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('grade__gte', 5), ('grade__lte', 10)), ('grade__isnull', True), _connector='OR'), name='exam_registration_grade_between_5_and_10_or_null')],
            },
        ),
    ]
