# Generated by Django 6.0.5 on 2026-07-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_professorprofile_studentprofile'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examregistration',
            name='exam_registration_grade_between_5_and_10_or_null',
        ),
        migrations.AddConstraint(
            model_name='examregistration',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='uq_exam_registration_student_exam'),
        ),
        migrations.AddConstraint(
            model_name='examregistration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grade__gte', 5), ('grade__lte', 10)), ('grade__isnull', True), _connector='OR'), name='exam_registration_grade_valid'),
        ),
    ]
