# Generated by Django 6.0.5 on 2026-07-19 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "exams",
            "0002_remove_examregistration_exam_registration_grade_between_5_and_10_or_null_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examregistration",
            name="uq_exam_registration_student_exam",
        ),
    ]
