# Generated by Django 6.0.7 on 2026-09-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_drop_user_username_column'),
        ('exams', '0003_remove_examregistration_uq_exam_registration_student_exam'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'canceled'), _negated=True), fields=('student', 'exam'), name='uq_exam_reg_non_canceled'),
        ),
    ]
