# Generated by Django 6.0.5 on 2026-07-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_exam_registration_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
