---
clusterName: student-service-cluster
talosVersion: v1.12.6
kubernetesVersion: v1.35.3
endpoint: https://192.168.1.50:6443

# Keep Talos-managed CNI disabled / Cilium is deployed through Flux.
cniConfig:
  name: none

controlPlane:
  talosImageURL: factory.talos.dev/nocloud-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba

worker:
  talosImageURL: factory.talos.dev/nocloud-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
  patches:
    - "@./patches/registry-harbor-ca.yaml"

nodes:
  - hostname: cp01
    controlPlane: true
    ipAddress: 192.168.1.50
    installDisk: /dev/vda
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: wn01
    controlPlane: false
    ipAddress: 192.168.1.51
    installDisk: /dev/vda
    patches:
      - "@./patches/workers/local-path-provisioner-volume.yaml"
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: wn02
    controlPlane: false
    ipAddress: 192.168.1.52
    installDisk: /dev/vda
    patches:
      - "@./patches/workers/local-path-provisioner-volume.yaml"
    networkInterfaces:
      - interface: eth0
        dhcp: true
