apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-scale-set
  namespace: flux-system
spec:
  dependsOn:
    - name: actions-runner-controller
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m
  path: ./infra/ci/actions-runner-scale-set
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
