apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-l2
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
  interval: 10m
  path: ./infra/networking/cilium-l2
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
