apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - gateway-api-source.yaml
  - gateway-api-crds.yaml
  - infra.yaml
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - cert-manager-issuers.yaml
  - actions-runner-controller.yaml
  - actions-runner-scale-set.yaml
  - cilium-l2.yaml
  - gateway-api.yaml
  - storage.yaml
  - harbor-certificates.yaml
  - harbor.yaml
  - student-service-database.yaml
  - student-service-migrations.yaml
  - student-service-backend.yaml
