apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: student-service-frontend
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-issuers
    - name: student-service-backend
    - name: gateway-api
  interval: 10m
  path: ./apps/student-service/frontend
  prune: true
  wait: true
  timeout: 10m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: student-service-frontend
      namespace: student-service
  sourceRef:
    kind: GitRepository
    name: flux-system
