apiVersion: v1
kind: Service
metadata:
  name: student-service-backend
  namespace: student-service
  labels:
    app.kubernetes.io/name: student-service-backend
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: student-service-backend
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
