apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: student-service-backend
  namespace: student-service
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: student-service-backend
      app.kubernetes.io/component: api
  endpoints:
    - port: metrics
      interval: 15s
