apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 30m
  releaseName: cnpg
  targetNamespace: cnpg-system
  storageNamespace: cnpg-system
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
    namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
